// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp4igY31GK2lO9cPgpBQM_HapdMmZrLFU',
    appId: '1:893229400340:web:0ae41a53b590f057cc8201',
    messagingSenderId: '893229400340',
    projectId: 'warood-f401a',
    authDomain: 'warood-f401a.firebaseapp.com',
    storageBucket: 'warood-f401a.appspot.com',
    measurementId: 'G-LN63MDN6XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVxsQ1AQDUMnUMaMCFFpbfLGlmGvvcq0o',
    appId: '1:893229400340:android:331b8d9321660722cc8201',
    messagingSenderId: '893229400340',
    projectId: 'warood-f401a',
    storageBucket: 'warood-f401a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkZoVz4ciK1YZQau7VE5-bIelUUfI-b4',
    appId: '1:893229400340:ios:1f98a4aa50c3d90fcc8201',
    messagingSenderId: '893229400340',
    projectId: 'warood-f401a',
    storageBucket: 'warood-f401a.appspot.com',
    iosClientId: '893229400340-3h18d94v5pn81ptnj4egrq2594ki117q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdkZoVz4ciK1YZQau7VE5-bIelUUfI-b4',
    appId: '1:893229400340:ios:1f98a4aa50c3d90fcc8201',
    messagingSenderId: '893229400340',
    projectId: 'warood-f401a',
    storageBucket: 'warood-f401a.appspot.com',
    iosClientId: '893229400340-3h18d94v5pn81ptnj4egrq2594ki117q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBase',
  );
}
