// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCANNDY6CYhiG5oxOrDgvZRcNNGB3BFDXc',
    appId: '1:4197140679:web:a4e71543bfd2164d31d6e2',
    messagingSenderId: '4197140679',
    projectId: 'warood-51e55',
    authDomain: 'warood-51e55.firebaseapp.com',
    storageBucket: 'warood-51e55.appspot.com',
    measurementId: 'G-GH6NQK2HHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgdsGczgWr19O1ImVrY85437mTVhc6V_4',
    appId: '1:4197140679:android:d44f095be67ccc6e31d6e2',
    messagingSenderId: '4197140679',
    projectId: 'warood-51e55',
    storageBucket: 'warood-51e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_jD8-NqKxFUGZeldrdLm00NxVM7o3wk',
    appId: '1:4197140679:ios:9a3844a9172036aa31d6e2',
    messagingSenderId: '4197140679',
    projectId: 'warood-51e55',
    storageBucket: 'warood-51e55.appspot.com',
    iosClientId: '4197140679-hl0k9c04q5vedaf7non85ekd642cberb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI_jD8-NqKxFUGZeldrdLm00NxVM7o3wk',
    appId: '1:4197140679:ios:9a3844a9172036aa31d6e2',
    messagingSenderId: '4197140679',
    projectId: 'warood-51e55',
    storageBucket: 'warood-51e55.appspot.com',
    iosClientId: '4197140679-hl0k9c04q5vedaf7non85ekd642cberb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBase',
  );
}
